// ── HEX DATABASE (from NotebookLM / Dolmenwood Campaign Book) ──
// Format: "CCRRR": { terrain, region, lostChance, encChance, tpCost, terrainClass }
// terrainClass: light | moderate | severe | aquatic | road
// tpCost on roads = 2; light=2; moderate=3; severe=4
// lostChance: on road = 0; light = 1; moderate = 2; severe = 3 (in-6)

const HEXES = {
"0101":{t:"Bog",r:"Northern Scratch",lc:2,ec:2,tp:3,tc:"moderate"},
"0102":{t:"Bog",r:"Northern Scratch",lc:2,ec:2,tp:3,tc:"moderate"},
"0103":{t:"Bog",r:"Northern Scratch",lc:2,ec:2,tp:3,tc:"moderate"},
"0105":{t:"Meadow",r:"High Wold",lc:1,ec:1,tp:2,tc:"light"},
"0106":{t:"Tangled forest",r:"High Wold",lc:2,ec:2,tp:3,tc:"moderate"},
"0107":{t:"Meadow",r:"High Wold",lc:1,ec:1,tp:2,tc:"light"},
"0108":{t:"Farmland",r:"High Wold",lc:1,ec:1,tp:2,tc:"light"},
"0109":{t:"Tangled forest",r:"High Wold",lc:2,ec:2,tp:3,tc:"moderate"},
"0110":{t:"Tangled forest",r:"High Wold",lc:2,ec:2,tp:3,tc:"moderate"},
"0111":{t:"Meadow",r:"High Wold",lc:1,ec:1,tp:2,tc:"light"},
"0201":{t:"Bog",r:"Northern Scratch",lc:2,ec:2,tp:3,tc:"moderate"},
"0202":{t:"Swamp",r:"Northern Scratch",lc:3,ec:3,tp:4,tc:"severe"},
"0203":{t:"Swamp",r:"Northern Scratch",lc:3,ec:3,tp:4,tc:"severe"},
"0204":{t:"Bog",r:"Northern Scratch / Dwelmfurgh",lc:2,ec:2,tp:3,tc:"moderate"},
"0205":{t:"Meadow",r:"High Wold / Dwelmfurgh",lc:1,ec:1,tp:2,tc:"light"},
"0206":{t:"Tangled forest",r:"High Wold / Dwelmfurgh",lc:2,ec:2,tp:3,tc:"moderate"},
"0207":{t:"Tangled forest",r:"High Wold / Dwelmfurgh",lc:2,ec:2,tp:3,tc:"moderate"},
"0208":{t:"Tangled forest",r:"High Wold",lc:2,ec:2,tp:3,tc:"moderate"},
"0209":{t:"Craggy forest",r:"High Wold",lc:3,ec:3,tp:4,tc:"severe"},
"0210":{t:"Hilly forest",r:"High Wold",lc:2,ec:2,tp:3,tc:"moderate"},
"0211":{t:"Meadow",r:"High Wold",lc:1,ec:1,tp:2,tc:"light"},
"0301":{t:"Bog",r:"Northern Scratch",lc:2,ec:2,tp:3,tc:"moderate"},
"0302":{t:"Bog",r:"Northern Scratch",lc:2,ec:2,tp:3,tc:"moderate"},
"0303":{t:"Bog",r:"Northern Scratch",lc:2,ec:2,tp:3,tc:"moderate"},
"0304":{t:"Tangled forest",r:"Northern Scratch / Dwelmfurgh",lc:2,ec:2,tp:3,tc:"moderate"},
"0305":{t:"Bog",r:"Dwelmfurgh",lc:2,ec:2,tp:3,tc:"moderate"},
"0306":{t:"Tangled forest",r:"Dwelmfurgh",lc:2,ec:2,tp:3,tc:"moderate"},
"0307":{t:"Hilly forest",r:"Dwelmfurgh",lc:2,ec:2,tp:3,tc:"moderate"},
"0308":{t:"Hilly forest",r:"High Wold / Dwelmfurgh",lc:2,ec:2,tp:3,tc:"moderate"},
"0309":{t:"Hilly forest",r:"High Wold",lc:2,ec:2,tp:3,tc:"moderate"},
"0310":{t:"Tangled forest",r:"High Wold",lc:2,ec:2,tp:3,tc:"moderate"},
"0311":{t:"Tangled forest",r:"High Wold",lc:2,ec:2,tp:3,tc:"moderate"},
"0312":{t:"Meadow",r:"High Wold",lc:1,ec:1,tp:2,tc:"light"},
"0401":{t:"Bog",r:"Northern Scratch",lc:2,ec:2,tp:3,tc:"moderate"},
"0402":{t:"Tangled forest",r:"Northern Scratch",lc:2,ec:2,tp:3,tc:"moderate"},
"0403":{t:"Tangled forest",r:"Northern Scratch / Dwelmfurgh",lc:2,ec:2,tp:3,tc:"moderate"},
"0404":{t:"Tangled forest",r:"Dwelmfurgh",lc:2,ec:2,tp:3,tc:"moderate"},
"0405":{t:"Craggy forest",r:"Dwelmfurgh",lc:3,ec:3,tp:4,tc:"severe"},
"0406":{t:"Tangled forest",r:"Dwelmfurgh",lc:2,ec:2,tp:3,tc:"moderate"},
"0407":{t:"Craggy forest",r:"Dwelmfurgh",lc:3,ec:3,tp:4,tc:"severe"},
"0408":{t:"Hilly forest",r:"Dwelmfurgh",lc:2,ec:2,tp:3,tc:"moderate"},
"0409":{t:"Hilly forest",r:"High Wold",lc:2,ec:2,tp:3,tc:"moderate"},
"0410":{t:"Tangled forest",r:"High Wold",lc:2,ec:2,tp:3,tc:"moderate"},
"0411":{t:"Meadow",r:"High Wold",lc:1,ec:1,tp:2,tc:"light"},
"0412":{t:"Meadow",r:"High Wold",lc:1,ec:1,tp:2,tc:"light"},
"0501":{t:"Bog",r:"Northern Scratch",lc:2,ec:2,tp:3,tc:"moderate"},
"0502":{t:"Tangled forest",r:"Northern Scratch",lc:2,ec:2,tp:3,tc:"moderate"},
"0503":{t:"Thorny forest",r:"Dwelmfurgh / Northern Scratch",lc:3,ec:3,tp:4,tc:"severe"},
"0504":{t:"Craggy forest",r:"Dwelmfurgh",lc:3,ec:3,tp:4,tc:"severe"},
"0506":{t:"Craggy forest",r:"Dwelmfurgh",lc:3,ec:3,tp:4,tc:"severe"},
"0507":{t:"Craggy forest",r:"Dwelmfurgh",lc:3,ec:3,tp:4,tc:"severe"},
"0508":{t:"Craggy forest",r:"Dwelmfurgh",lc:3,ec:3,tp:4,tc:"severe"},
"0509":{t:"Hilly forest",r:"High Wold / Dwelmfurgh",lc:2,ec:2,tp:3,tc:"moderate"},
"0510":{t:"Tangled forest",r:"Dwelmfurgh",lc:2,ec:2,tp:3,tc:"moderate"},
"0512":{t:"Farmland",r:"High Wold",lc:1,ec:1,tp:2,tc:"light"},
"0601":{t:"Hills",r:"Table Downs",lc:1,ec:1,tp:2,tc:"light"},
"0602":{t:"Tangled forest",r:"Nagwood",lc:2,ec:2,tp:3,tc:"moderate"},
"0603":{t:"Thorny forest",r:"Dwelmfurgh / Northern Scratch",lc:3,ec:3,tp:4,tc:"severe"},
"0604":{t:"Thorny forest",r:"Dwelmfurgh",lc:3,ec:3,tp:4,tc:"severe"},
"0605":{t:"Aquatic",r:"Dwelmfurgh",lc:2,ec:2,tp:3,tc:"aquatic"},
"0606":{t:"Aquatic / Craggy forest",r:"Dwelmfurgh",lc:2,ec:2,tp:3,tc:"aquatic"},
"0607":{t:"Craggy forest",r:"Dwelmfurgh",lc:3,ec:3,tp:4,tc:"severe"},
"0608":{t:"Craggy forest",r:"Dwelmfurgh",lc:3,ec:3,tp:4,tc:"severe"},
"0609":{t:"Hilly forest",r:"High Wold",lc:2,ec:2,tp:3,tc:"moderate"},
"0610":{t:"Hills",r:"High Wold",lc:1,ec:1,tp:2,tc:"light"},
"0611":{t:"Meadow",r:"High Wold",lc:1,ec:1,tp:2,tc:"light"},
"0612":{t:"Hills",r:"Table Downs",lc:1,ec:1,tp:2,tc:"light"},
"0701":{t:"Hills",r:"Table Downs",lc:1,ec:1,tp:2,tc:"light"},
"0702":{t:"Tangled forest",r:"Nagwood",lc:2,ec:2,tp:3,tc:"moderate"},
"0703":{t:"Tangled forest",r:"Dwelmfurgh / Nagwood",lc:2,ec:2,tp:3,tc:"moderate"},
"0704":{t:"Tangled forest",r:"Dwelmfurgh",lc:2,ec:2,tp:3,tc:"moderate"},
"0705":{t:"Aquatic",r:"Dwelmfurgh",lc:2,ec:2,tp:3,tc:"aquatic"},
"0706":{t:"Aquatic / Tangled forest",r:"Dwelmfurgh",lc:2,ec:2,tp:3,tc:"aquatic"},
"0707":{t:"Craggy forest",r:"High Wold / Dwelmfurgh",lc:3,ec:3,tp:4,tc:"severe"},
"0708":{t:"Tangled forest",r:"High Wold",lc:2,ec:2,tp:3,tc:"moderate"},
"0709":{t:"Farmland",r:"High Wold",lc:1,ec:1,tp:2,tc:"light"},
"0710":{t:"Hills",r:"High Wold",lc:1,ec:1,tp:2,tc:"light"},
"0711":{t:"Hills",r:"Table Downs",lc:1,ec:1,tp:2,tc:"light"},
"0801":{t:"Tangled forest",r:"Nagwood",lc:2,ec:2,tp:3,tc:"moderate"},
"0802":{t:"Thorny forest",r:"Nagwood",lc:3,ec:3,tp:4,tc:"severe"},
"0803":{t:"Thorny forest",r:"Nagwood / Dwelmfurgh",lc:3,ec:3,tp:4,tc:"severe"},
"0804":{t:"Tangled forest",r:"Aldweald / Dwelmfurgh",lc:2,ec:2,tp:3,tc:"moderate"},
"0805":{t:"Aquatic / Tangled forest",r:"Aldweald / Dwelmfurgh",lc:2,ec:2,tp:3,tc:"aquatic"},
"0806":{t:"Swamp",r:"Dwelmfurgh / Hag's Addle",lc:3,ec:3,tp:4,tc:"severe"},
"0807":{t:"Craggy forest",r:"High Wold",lc:3,ec:3,tp:4,tc:"severe"},
"0808":{t:"Open forest",r:"High Wold",lc:1,ec:1,tp:2,tc:"light"},
"0809":{t:"Open forest",r:"High Wold",lc:1,ec:1,tp:2,tc:"light"},
"0810":{t:"Hills",r:"High Wold",lc:1,ec:1,tp:2,tc:"light"},
"0811":{t:"Meadow",r:"High Wold",lc:1,ec:1,tp:2,tc:"light"},
"0812":{t:"Hills",r:"Table Downs",lc:1,ec:1,tp:2,tc:"light"},
"0901":{t:"Tangled forest",r:"Nagwood",lc:2,ec:2,tp:3,tc:"moderate"},
"0902":{t:"Tangled forest",r:"Nagwood",lc:2,ec:2,tp:3,tc:"moderate"},
"0903":{t:"Thorny forest",r:"Nagwood",lc:3,ec:3,tp:4,tc:"severe"},
"0904":{t:"Tangled forest",r:"Valley of Wise Beasts",lc:2,ec:2,tp:3,tc:"moderate"},
"0905":{t:"Craggy forest",r:"Aldweald",lc:3,ec:3,tp:4,tc:"severe"},
"0906":{t:"Tangled forest",r:"Aldweald",lc:2,ec:2,tp:3,tc:"moderate"},
"0907":{t:"Swamp",r:"Hag's Addle",lc:3,ec:3,tp:4,tc:"severe"},
"0909":{t:"Tangled forest",r:"Aldweald",lc:2,ec:2,tp:3,tc:"moderate"},
"0910":{t:"Tangled forest",r:"High Wold",lc:2,ec:2,tp:3,tc:"moderate"},
"0911":{t:"Tangled forest",r:"High Wold",lc:2,ec:2,tp:3,tc:"moderate"},
"1001":{t:"Tangled forest",r:"Nagwood",lc:2,ec:2,tp:3,tc:"moderate"},
"1002":{t:"Bog",r:"Fever Marsh",lc:2,ec:2,tp:3,tc:"moderate"},
"1003":{t:"Thorny forest",r:"Nagwood",lc:3,ec:3,tp:4,tc:"severe"},
"1004":{t:"Tangled forest",r:"Valley of Wise Beasts",lc:2,ec:2,tp:3,tc:"moderate"},
"1005":{t:"Tangled forest",r:"Aldweald",lc:2,ec:2,tp:3,tc:"moderate"},
"1006":{t:"Craggy forest",r:"Aldweald",lc:3,ec:3,tp:4,tc:"severe"},
"1007":{t:"Tangled forest",r:"Aldweald",lc:2,ec:2,tp:3,tc:"moderate"},
"1008":{t:"Swamp",r:"Hag's Addle",lc:3,ec:3,tp:4,tc:"severe"},
"1009":{t:"Tangled forest",r:"High Wold",lc:2,ec:2,tp:3,tc:"moderate"},
"1010":{t:"Tangled forest",r:"High Wold",lc:2,ec:2,tp:3,tc:"moderate"},
"1011":{t:"Tangled forest",r:"High Wold",lc:2,ec:2,tp:3,tc:"moderate"},
"1012":{t:"Meadow",r:"High Wold",lc:1,ec:1,tp:2,tc:"light"},
"1101":{t:"Tangled forest",r:"Nagwood",lc:2,ec:2,tp:3,tc:"moderate"},
"1102":{t:"Bog",r:"Fever Marsh",lc:2,ec:2,tp:3,tc:"moderate"},
"1103":{t:"Bog",r:"Fever Marsh",lc:2,ec:2,tp:3,tc:"moderate"},
"1104":{t:"Tangled forest",r:"Valley of Wise Beasts",lc:2,ec:2,tp:3,tc:"moderate"},
"1105":{t:"Craggy forest",r:"Aldweald",lc:3,ec:3,tp:4,tc:"severe"},
"1106":{t:"Tangled forest",r:"Aldweald",lc:2,ec:2,tp:3,tc:"moderate"},
"1107":{t:"Tangled forest",r:"Aldweald",lc:2,ec:2,tp:3,tc:"moderate"},
"1108":{t:"Tangled forest",r:"Aldweald",lc:2,ec:2,tp:3,tc:"moderate"},
"1109":{t:"Swamp",r:"Hag's Addle",lc:3,ec:3,tp:4,tc:"severe"},
"1110":{t:"Tangled forest",r:"High Wold / Aldweald",lc:2,ec:2,tp:3,tc:"moderate"},
"1111":{t:"Tangled forest",r:"Aldweald / High Wold",lc:2,ec:2,tp:3,tc:"moderate"},
"1201":{t:"Hills",r:"Table Downs",lc:1,ec:1,tp:2,tc:"light"},
"1202":{t:"Swamp",r:"Fever Marsh",lc:3,ec:3,tp:4,tc:"severe"},
"1203":{t:"Tangled forest",r:"Valley of Wise Beasts",lc:2,ec:2,tp:3,tc:"moderate"},
"1204":{t:"Craggy forest",r:"Aldweald",lc:3,ec:3,tp:4,tc:"severe"},
"1205":{t:"Tangled forest",r:"Aldweald",lc:2,ec:2,tp:3,tc:"moderate"},
"1206":{t:"Tangled forest",r:"Aldweald",lc:2,ec:2,tp:3,tc:"moderate"},
"1207":{t:"Tangled forest",r:"Aldweald",lc:2,ec:2,tp:3,tc:"moderate"},
"1208":{t:"Tangled forest",r:"Aldweald",lc:2,ec:2,tp:3,tc:"moderate"},
"1209":{t:"Tangled forest",r:"Aldweald",lc:2,ec:2,tp:3,tc:"moderate"},
"1210":{t:"Open forest",r:"Aldweald",lc:1,ec:1,tp:2,tc:"light"},
"1211":{t:"Open forest",r:"Aldweald",lc:1,ec:1,tp:2,tc:"light"},
"1212":{t:"Meadow",r:"Tithelands",lc:1,ec:1,tp:2,tc:"light"},
"1301":{t:"Hills",r:"Table Downs",lc:1,ec:1,tp:2,tc:"light"},
"1302":{t:"Tangled forest",r:"Aldweald",lc:2,ec:2,tp:3,tc:"moderate"},
"1303":{t:"Tangled forest",r:"Aldweald",lc:2,ec:2,tp:3,tc:"moderate"},
"1304":{t:"Craggy forest",r:"Aldweald",lc:3,ec:3,tp:4,tc:"severe"},
"1305":{t:"Tangled forest",r:"Aldweald",lc:2,ec:2,tp:3,tc:"moderate"},
"1306":{t:"Tangled forest",r:"Aldweald",lc:2,ec:2,tp:3,tc:"moderate"},
"1307":{t:"Open forest",r:"Aldweald",lc:1,ec:1,tp:2,tc:"light"},
"1308":{t:"Open forest",r:"Aldweald",lc:1,ec:1,tp:2,tc:"light"},
"1309":{t:"Tangled forest",r:"Aldweald",lc:2,ec:2,tp:3,tc:"moderate"},
"1310":{t:"Tangled forest",r:"Aldweald",lc:2,ec:2,tp:3,tc:"moderate"},
"1311":{t:"Meadow",r:"Tithelands",lc:1,ec:1,tp:2,tc:"light"},
"1401":{t:"Hills",r:"Table Downs",lc:1,ec:1,tp:2,tc:"light"},
"1402":{t:"Tangled forest",r:"Aldweald",lc:2,ec:2,tp:3,tc:"moderate"},
"1403":{t:"Tangled forest",r:"Aldweald",lc:2,ec:2,tp:3,tc:"moderate"},
"1404":{t:"Boggy forest",r:"Aldweald",lc:3,ec:3,tp:4,tc:"severe"},
"1405":{t:"Fungal forest",r:"Mulchgrove",lc:1,ec:1,tp:2,tc:"light"},
"1406":{t:"Boggy forest",r:"Aldweald",lc:3,ec:3,tp:4,tc:"severe"},
"1407":{t:"Meadow",r:"Tithelands",lc:1,ec:1,tp:2,tc:"light"},
"1408":{t:"Tangled forest",r:"Aldweald",lc:2,ec:2,tp:3,tc:"moderate"},
"1409":{t:"Meadow",r:"Tithelands",lc:1,ec:1,tp:2,tc:"light"},
"1410":{t:"Hills",r:"Table Downs",lc:1,ec:1,tp:2,tc:"light"},
"1501":{t:"Hills",r:"Table Downs",lc:1,ec:1,tp:2,tc:"light"},
"1502":{t:"Hilly forest",r:"Aldweald",lc:2,ec:2,tp:3,tc:"moderate"},
"1503":{t:"Tangled forest",r:"Aldweald",lc:2,ec:2,tp:3,tc:"moderate"},
"1504":{t:"Boggy forest",r:"Aldweald",lc:3,ec:3,tp:4,tc:"severe"},
"1505":{t:"Fungal forest",r:"Mulchgrove",lc:1,ec:1,tp:2,tc:"light"},
"1507":{t:"Boggy forest",r:"Aldweald",lc:3,ec:3,tp:4,tc:"severe"},
"1509":{t:"Farmland",r:"Tithelands",lc:1,ec:1,tp:2,tc:"light"},
"1602":{t:"Hilly forest",r:"Aldweald",lc:2,ec:2,tp:3,tc:"moderate"},
"1603":{t:"Boggy forest",r:"Aldweald",lc:3,ec:3,tp:4,tc:"severe"},
"1604":{t:"Boggy forest",r:"Mulchgrove",lc:3,ec:3,tp:4,tc:"severe"},
"1605":{t:"Fungal forest",r:"Mulchgrove",lc:1,ec:1,tp:2,tc:"light"},
"1606":{t:"Tangled forest",r:"Aldweald",lc:2,ec:2,tp:3,tc:"moderate"},
"1607":{t:"Open forest",r:"Aldweald",lc:1,ec:1,tp:2,tc:"light"},
"1701":{t:"Hills",r:"Table Downs",lc:1,ec:1,tp:2,tc:"light"},
"1702":{t:"Hilly forest",r:"Aldweald",lc:2,ec:2,tp:3,tc:"moderate"},
"1703":{t:"Boggy forest",r:"Aldweald",lc:3,ec:3,tp:4,tc:"severe"},
"1704":{t:"Fungal forest",r:"Mulchgrove",lc:1,ec:1,tp:2,tc:"light"},
"1705":{t:"Boggy forest",r:"Mulchgrove",lc:3,ec:3,tp:4,tc:"severe"},
"1706":{t:"Open forest",r:"Aldweald",lc:1,ec:1,tp:2,tc:"light"},
"1707":{t:"Hilly forest",r:"Aldweald",lc:2,ec:2,tp:3,tc:"moderate"},
"1801":{t:"Hilly forest",r:"Aldweald",lc:2,ec:2,tp:3,tc:"moderate"},
"1802":{t:"Boggy forest",r:"Aldweald",lc:3,ec:3,tp:4,tc:"severe"},
"1803":{t:"Boggy forest",r:"Aldweald",lc:3,ec:3,tp:4,tc:"severe"},
"1804":{t:"Boggy forest",r:"Aldweald",lc:3,ec:3,tp:4,tc:"severe"},
"1805":{t:"Tangled forest",r:"Aldweald",lc:2,ec:2,tp:3,tc:"moderate"},
"1901":{t:"Hills",r:"Table Downs",lc:1,ec:1,tp:2,tc:"light"},
"1903":{t:"Hilly forest",r:"Aldweald",lc:2,ec:2,tp:3,tc:"moderate"},
"1905":{t:"Tangled forest",r:"Aldweald",lc:2,ec:2,tp:3,tc:"moderate"},
"1906":{t:"Open forest",r:"Aldweald",lc:1,ec:1,tp:2,tc:"light"},
};
